FROM node:lts-alpine as build

WORKDIR /src

COPY d450-public/package.json ./
RUN npm install

COPY d450-public/. ./
RUN npm run build


FROM nginx:stable-alpine
COPY --from=build /src/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
